package com.example.sensormonitor.model

data class SensorUiState(
    val isRunning: Boolean = false,
    val statusText: String = "",
    val latitude: Double? = null,
    val longitude: Double? = null,
    val altitude: Double? = null,
    val accelX: Float = 0f,
    val accelY: Float = 0f,
    val accelZ: Float = 0f,
    val gyroX: Float = 0f,
    val gyroY: Float = 0f,
    val gyroZ: Float = 0f,
    val yaw: Float = 0f,
    val pitch: Float = 0f,
    val roll: Float = 0f,
    val speed: Float = 0f,
    val usbGpsConnected: Boolean = false,
    val usbImuConnected: Boolean = false,
    val magX: Float = 0f,
    val magY: Float = 0f,
    val magZ: Float = 0f,
    val pressure: Float = 0f,
    val height: Float = 0f,
    val quatW: Float = 0f,
    val quatX: Float = 0f,
    val quatY: Float = 0f,
    val quatZ: Float = 0f,
    val svCount: Int = 0,
    val pdop: Float = 0f,
    val hdop: Float = 0f,
    val vdop: Float = 0f,
)
